import { cp, mkdir, readFile, writeFile, rm } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const repo = path.resolve(root, '..');
const output = path.join(root, 'build/engine-web');
const destination = path.join(root, 'build/viewer-resources/viewers/ply');
const build = spawnSync('npm', ['run', 'build', '--workspace=engine', '--', '--output-path', output], { cwd: repo, stdio: 'inherit' });
if (build.status !== 0) throw new Error('3D engine build failed');
await rm(destination, { recursive: true, force: true });
await mkdir(destination, { recursive: true });
await cp(output, destination, { recursive: true });
const index = path.join(destination, 'index.html');
let html = await readFile(index, 'utf8');
html = html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, script => /plausible|analytics\.re4vive/.test(script) ? '' : script);
html = html.replace(/<link\b[^>]*rel="(?:manifest|canonical)"[^>]*>/gi, '');
html = html.replace(/<div class="bottom-right-nav">[\s\S]*?<\/div>/, '');
html = html.replace('</body>', '<script src="../bridge.js" defer></script></body>');
await writeFile(index, html);
await import('./collect-notices.mjs');
console.log('Bundled the local 3D engine for JetBrains; no TIFF repository required.');
