"""Generate the tool reference without importing MCP or starting a renderer."""
import ast
from pathlib import Path
import sys
import textwrap

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'packages/python/viz3d/mcp_server.py'
OUTPUT = ROOT / 'docs/mcp-tools.md'


def generate():
    tree = ast.parse(SOURCE.read_text())
    tools = [node for node in ast.walk(tree) if isinstance(node, ast.FunctionDef)
             and any(isinstance(d, ast.Call) and isinstance(d.func, ast.Name)
                     and d.func.id == 'tool' for d in node.decorator_list)
             and node.name not in {'read_viewer_data', 'submit_viewer_reply'}]
    tools.sort(key=lambda node: node.lineno)
    point_type = next(ast.unparse(node.value) for node in ast.walk(tree)
                      if isinstance(node, ast.Assign) and any(isinstance(t, ast.Name)
                      and t.id == 'points_type' for t in node.targets))
    lines = ['# MCP tool reference', '',
             'This reference describes the current development checkout. Installed releases',
             'may expose fewer tools; the connected server’s tool schema is authoritative.', '',
             'Start with [setup](../packages/python/MCP.md) and the',
             '[task walkthroughs](mcp-workflows.md). These are MCP tool arguments, not',
             'functions to import into a Python script. The MCP client supplies context.', '',
             '<!-- Generated by python3 scripts/generate-mcp-docs.py; edit the server docstrings/signatures. -->', '',
             '## Tool index', '']
    lines += [f'- [{node.name}](#{node.name.replace("_", "-")})' for node in tools]
    for node in tools:
        lines += ['', f'## {node.name.replace("_", " ")}', '', f'Tool: `{node.name}`', '']
        for paragraph in (ast.get_docstring(node) or '').split('\n\n'):
            lines += [textwrap.fill(paragraph, width=80), '']
        lines += ['```python', f'{node.name}(']
        defaults = [None] * (len(node.args.args) - len(node.args.defaults)) + node.args.defaults
        for arg, default in zip(node.args.args, defaults):
            if arg.arg == 'ctx':
                continue
            annotation = ast.unparse(arg.annotation).replace('points_type', point_type) if arg.annotation else 'Any'
            suffix = '' if default is None else ' = ' + ast.unparse(default)
            lines += [f'    {arg.arg}: {annotation}{suffix},']
        lines += [')', '```']
    lines += ['', '## Reading argument types', '',
              '`Literal[...]` lists accepted values. `Annotated[..., Field(...)]` records',
              'validation limits such as minimum/maximum values and list lengths.',
              '`None` means an optional argument can be omitted. Most editing tools accept',
              '`detail="full"` when a more complete state reply is useful.', '',
              'The app-only tools `read_viewer_data` and `submit_viewer_reply` carry renderer',
              'assets and replies; agents should use the public tools above.', '']
    return '\n'.join(lines)


if __name__ == '__main__':
    result = generate()
    if '--check' in sys.argv:
        if not OUTPUT.exists() or OUTPUT.read_text() != result:
            sys.exit('MCP reference is stale. Run python3 scripts/generate-mcp-docs.py')
        print('MCP tool reference matches server definitions.')
    else:
        OUTPUT.write_text(result)
        print(OUTPUT.relative_to(ROOT))
